production:
  lets:
    enable: true
    cmd: "certbot certonly"
    email: "tlab-admin@googlegroups.com"
    webroot_dir: "/var/www/lets"
  nginx:
    ssl: true
    dummy_ssl: false
    app_log: true
    conf_dir: "/etc/nginx/conf.d/api-reg-hosts"
    reload_cmd: "systemctl reload nginx"
development:
  lets:
    enable: true
    cmd: "certbot certonly --staging"
    email: "moufmofu@shippo.com"
    webroot_dir: "/var/www/lets"
  nginx:
    ssl: true
    dummy_ssl : false
    app_log: true
    conf_dir: "./tmp"
    reload_cmd: "echo systemctl reload nginx"
