production:
  lets:
    enable: false
    cmd: "certbot certonly"
    email: "tlab-admin@googlegroups.com"
    webroot_dir: "/var/www/lets/"
  nginx:
    ssl: true
    dummy_ssl: true
    app_log: true
    conf_dir: "/etc/nginx/conf.d/api-reg-hosts"
    reload_cmd: "systemctl reload nginx"
  domain:
    base: "t-lab.cs.teu.ac.jp"
    internal_base: "k8s-nodes.internal.t-lab.cs.teu.ac.jp"
develop:
  lets:
    enable: true
    cmd: "echo"
    email: "moufmofu@shippo.com"
    webroot_dir: "./"
  nginx:
    ssl: true
    dummy_ssl : false
    app_log: true
    conf_dir: "."
    reload_cmd: "echo systemctl reload nginx"
  domain:
    base: "t-lab.cs.teu.ac.jp"
    internal_base: "k8s-nodes.internal.t-lab.cs.teu.ac.jp"
